### PR TITLE
Fix for nswbuff-kill-this-buffer

### PR DESCRIPTION
**Pull request by lerouxrgd**
As I tried to use `nswbuff-kill-this-buffer` by binding it to `k` in `nswbuff-override-map` I realised it is quite buggy.

After a long debugging session I came up with this fix, let me know what you think of it.

I tested it with many situations, particularly with and without `nswbuff-display-intermediate-buffers`, but I could have missed an edge case ...

### CODE REVIEW

**Comment by joostkremers** [comment]
Thanks!

> As I tried to use `nswbuff-kill-this-buffer` by binding it to `k` in `nswbuff-override-map` I realised it is quite buggy.

Yeah, I'm not surprised. I initially thought it would be a good idea but then I found it not as convenient as I had thought, so I never really used it.
 
I'd like to run this branch for a day or two to see if any unexpected issues turn up. I don't expect any, but there are a few changes outside `nswbuff-kill-this-buffer`, so you never know.

**Comment by lerouxrgd** [comment]
Actually I realized that we need the buffer switching in `nswbuff-discard-status-window` so I put it back.

**Comment by joostkremers** [comment]
> Actually I realized that we need the buffer switching in `nswbuff-discard-status-window` so I put it back.

What have you observed? I haven't noticed any strange behaviour so far.

**Comment by lerouxrgd** [comment]
It changed the order of the buffer list that is displayed.

If you have `A | B | C` and switch to `B` you should have `B | A | C` because `A` is the more recent one. With my change it was something like `B | C | A` which is annoying with many buffers (because you can't easily find the previous one).

**Comment by joostkremers** [comment]
I see. That's important to get right, I agree.

I'll merge this now as it seems to work well enough. Thanks for submitting the patch!

**Pull request merged**
