### PR TITLE
Add minibuffer layout option for status info

### LINKED ISSUE #2: Configure status window height
Would it be possible to customise the height of the status window? 

Now it looks like this:

Ideally, I'd like to have it smaller. Something like:

### PR DESCRIPTION
**Pull request by lerouxrgd**
Add a minibuffer layout option that can be set as follows: `(setq nswbuff-status-window-layout 'minibuffer)`.

Fixes #2

### CODE REVIEW

**Comment by joostkremers** [comment]
Thanks!

I only tested it a little bit, so please report any issues you run into.

**Comment by joostkremers** [comment]
Hmm, a little more testing shows that the minibuffer isn't emptied when switching ends. Not sure how to fix that...

**Comment by lerouxrgd** [comment]
For me it gets emptied at the end if switching (after both the timer or a key stroke).

I explicitly clean it up only in `nswbuff-discard-status-window` with `(with-current-buffer buffer (erase-buffer))`, but maybe we need to do the same thing in `nswbuff-maybe-discard-status-window` (I didn't do it as it looked fine without it for me).

How can I reproduce the not emptied minibuffer case ? Simply switching between two buffers in your case ?

**Comment by joostkremers** [comment]
> For me it gets emptied at the end if switching (after both the timer or a key stroke).

In my case, the buffer list remains visible. If some message is displayed in the echo area or the minibuffer is used for something else, it disappears, but as soon as I start interacting with the buffer (typing something, moving the cursor), the buffer list reappears, even though I'm not switching buffers.

> I explicitly clean it up only in `nswbuff-discard-status-window` with `(with-current-buffer buffer (erase-buffer))`, but maybe we need to do the same thing in `nswbuff-maybe-discard-status-window` (I didn't do it as it looked fine without it for me).

Yes, it all looks fine to me as well. `nswbuff-maybe-discard-status-window` calls `nswbuff-discard-status-window` if it reaches the conclusion that the status window must be discarded, so it shouldn't be necessary to erase the buffer in `nswbuff-maybe-discard-status-window`.

> How can I reproduce the not emptied minibuffer case ? Simply switching between two buffers in your case ?

Yes. I just tried it with (emacs-sandbox.sh)[https://github.com/alphapapa/emacs-sandbox.sh], and the problem still occurs, so it's not something to do with my setup.

What Emacs version are you using? I have Emacs 27.1.90.

**Comment by lerouxrgd** [comment]
Very strange ...

I am using Emacs 27.1 on ArchLinux (installed with the package manager).

I tried with `emacs-sandbox.sh` and it works fine, I have the same (correct) behavior as with my custom config, that is minibuffer is emptied after switching (timer or key stroke).
I started it like this: `./emacs-sandox.sh -d ./emacs.d` where in `./emacs.d` I have a single `init.el` file which is as follows:

```elisp
;; As of Emacs 27 it is no longer necessary to call `package-initialize'
(setq package--initialized t)

(require 'package)
(setq package-archives
      '(("gnu"          . "https://elpa.gnu.org/packages/")
        ("melpa"        . "https://melpa.org/packages/")
        ("melpa-stable" . "https://stable.melpa.org/packages/")))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package use-package
  :config (setq use-package-always-ensure t))

(use-package nswbuff
  :load-path "/home/raru/dev/workspaces/emacs/nswbuff"
  :bind (("C-<tab>"         . nswbuff-switch-to-next-buffer)
         ("<C-iso-lefttab>" . nswbuff-switch-to-previous-buffer))
  :config
  (setq nswbuff-display-intermediate-buffers t
        nswbuff-status-window-layout 'minibuffer))
```

Note that `:load-path` is where I git cloned the latest master version locally.

Did you use `emacs-sandbox.sh` in a similar way ? Do you still have the same wrong behavior with the config above ?

**Comment by joostkremers** [comment]
Very strange indeed...

I just do `./emacs-sandbox.sh` and then `M-x package-install RET nswbuff RET`. (The sandbox sets up GNU Elpa and Melpa, so you can install packages right away.) It shouldn't make any difference though.

I'm following the `emacs-27` branch from the Git repo, so perhaps there is some commit between the released version and the latest commit that messes things up. I'll try out the latest release and see what that gives me.

**Comment by lerouxrgd** [comment]
Ok I can reproduce with your method with `emacs-sandbox.sh`, I'll try to debug it.

**Comment by joostkremers** [comment]
The effect seems to go away when I restart Emacs... So setting `nswbuff-status-window-layout` to `minibuffer` in a running session gets me the strange effect, but when set it in my `init.el` and then restart Emacs, everything is fine.

**Comment by lerouxrgd** [comment]
Yes I observed the same behavior, but I think I found the issue.

When the issue happens `(buffer-name (window-buffer (minibuffer-window)))` returns `" *nswbuff*"` instead of `" *Minibuf-0*"`.

The reason is that in `nswbuff-show-status-window` we set `(set-window-buffer window (current-buffer))` where window is `(minibuffer-window)` and `(current-buffer)` is obtained through `nswbuff-get-status-buffer` which depends on `nswbuff-status-buffer` which by default is nil and will stay nill if from the start `nswbuff-status-window-layout` is set to `minibuffer` but will not be nill and will actually point to `" *nswbuff*"` otherwise as this buffer will always be alive since in my PR in `nswbuff-discard-status-window` I replaced `(if buffer (kill-buffer buffer))` with `(if buffer (with-current-buffer buffer (erase-buffer)))`.

So this last change is the reason why the edge-case of switching `nswbuff-status-window-layout` in a live session prevents the minibuffer to get emptied afterwards.

I will send another PR that fixes it shortly (I have tested it with `emacs-sandbox.sh`).

**Comment by joostkremers** [comment]
Thanks! I added a two questions about the code, would appreciate your input.

**Pull request merged**
